version: '2'

services:
    # kafka cluster
    kafka-cluster:
        image: landoop/fast-data-dev:cp3.3.0
        environment:
            ADV_HOST: 127.0.0.1
            # disable runing tests <-- running fast
            RUNTESTS: 0
        ports:
            # zookeeper
            - 2181:2181
            # landoop UI
            - 3030:3030
            # REST Proxy, schema registry, kafka connect ports
            - 8081-8083:8081-8083
            # jmx ports
            - 9581-9585:9581-9585
            #kafka broker
            - 9092:9092

    # elasticsearch
    elasticsearch:
        image: itzg/elasticsearch:2.4.3
        environment:
            PLUGINS: appbaseio/dejavu
            OPTS: -Dindex.number_of_shards=1
        ports:
            - "9200:3200"

    # postgres
    postgres:
        image: postgres:9.5-alpine
        environment:
            # defind credentials
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            # define database
            POSTGRES_DB: postgres
        ports:
            # postgres port
            - 5432:5432